on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can specify the version you need

      # Install dependencies
      - name: Install dependencies
        run: |
          npm ci  # Or npm install if you're not using a lock file

      # Install Cypress
      - name: Install Cypress
        run: npm install cypress --save-dev

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run
