name: Cypress Tests

on:
  repository_dispatch:
    types:
      - trigger-cypress-tests  # Custom event type to trigger Cypress tests

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from Repo Automotics
        uses: actions/checkout@v2

      # Set up Node.js (required for Cypress)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version used by your Cypress project

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Cypress
      - name: Install Cypress
        run: npm install cypress --save-dev

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run 
